### ISSUE TITLE
[Feedback] Per contact hours

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#10]
What if I know my contact is a night owl? Or I know their working hours (in a coworker situation )? Might be nice to be able to shift their curve to represent the times that person is available 

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
Hum yeah, I could add a couple of input in the contact edition screen to select the time for both - or default to the sunrise/sunset times

**Comment by mathieudutour** [comment]
Would that conflict with #7?

**Comment by paintedbicycle** [comment]
It could. (And again don't be sky to just close some of these "ideas").

I guess stepping back, I sort of ask myself, "How would I use this?". And I think the answer is that I'd use it to answer the questions "Should I text my friend David right now, or should I wait?". 

And so the ideas around:
- Quickly searching for David
- More accurately showing David's true "waking hours"

Come from that.


I could see a really pretty interaction where you can drag the curve left or right to adjust :)

**Comment by mathieudutour** [comment]
> I could see a really pretty interaction where you can drag the curve left or right to adjust :)

Exactly what I mentioned in #5! Do you think that #5 + this + #8 would remove the need for #7 ?

**Comment by paintedbicycle** [comment]
Haha yeah I went to that tweet after writing this up. Nice to see multiple thoughts on the same thing.

Yeah, I'd try it out. I think #7 is likely less important, especially if you can auto sort by "wake time".

**Comment by mathieudutour** [comment]
fixed
