### ISSUE TITLE
[Feedback] Selecting a country with multiple timezones

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#12]
If I select “Canada” as a location for my contact, it seems to just choose Pacific Time. However there are multiple time zones in Canada. So the app silently fails - maybe it should ask me after selecting Canada which time zone. Or, in the list have “Canada - Pacific Time” or similar. 

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
That's tricky. The search is provided by Apple, the same that is found in Maps. I don't really have a way of knowing whether what you search for was a country, or a city, or a street, etc..

But maybe I could clear some confusion by showing a map with the selected location

**Comment by paintedbicycle** [comment]
Hmm, no if I choose "USA" and I'm given LA time, that's not clear, even with a map. Is there any way to detect what type of location is returned from Apple? And just filter out Countries? I like being able to search for "Brazil" if I know they live there and I don't know their city, but if it's going to cause bad data I'm not sure it's worth it

**Comment by mathieudutour** [comment]
If I choose "USA", I'm right in the middle, in Nebraska - and -7 instead of -9. If you tap on the contact, it should show the map already so you can check where it is.

No I can't filter out countries, the only choice I have is "placemark" or "address".

**Comment by paintedbicycle** [comment]
Ah ok - I only guessed on the LA thing because of what I thought happened when I clicked Canada. Ok dang, guess we're stuck on this one

**Comment by mathieudutour** [comment]
Added a map just below to input to hopefully make it clearer
