### ISSUE TITLE
Custom rise/set times not sticking on Mac

### ISSUE THREAD

**Issue by forgottentowel** [mathieudutour/TimeLines#27]
Custom rise/set time values don't seem to stick on Mac:

Manage Contacts > Select Contact > Edit > change rise/set times > Done > rise/set times revert to default values

**Comment by mathieudutour** [comment]
Hum I haven't been able to reproduce that but I did find a bug where the time you set would be offset by your own timezone, maybe that's what's happening?

**Comment by mathieudutour** [comment]
publishing a new version for the aforementioned bug right now

**Comment by forgottentowel** [comment]
Just checked and it does indeed seem to be an offset problem. If I enter values 2h ahead of the ones I want (for a time zone 6h behind) then it saves the correct values.

**Comment by mathieudutour** [comment]
Cool. I'll close this then, the version is in review and should be published soon-ish
