### ISSUE TITLE
Great app. Analogue Clock

### ISSUE THREAD

**Issue by ajkarande** [mathieudutour/TimeLines#31]
Hi,

Just tried your new app. Good design, simple and shows good data points. 

Can we some widget designs like the attachment ones?

![image](https://user-images.githubusercontent.com/48931531/81463986-14490480-918c-11ea-9a49-402651e87d44.jpeg)

Thanks
Ajay

**Comment by mathieudutour** [comment]
The whole point of this app is to show a time line. If you want an analog clock using the one you are already using?

I think I'll say no to that one to keep the app simple
