### ISSUE TITLE
Issues with extreme latitudes

### ISSUE THREAD

**Issue by strey1998** [mathieudutour/TimeLines#35]
The sunrise/sunset graphics do not properly handle certain solar behavior in areas far from the equator. Two examples:

1. For my friend in Anchorage, Alaska, dusk is at 12:48 AM, dawn at 3:05 AM. The graphic does not handle the post-midnight dusk properly, instead showing a rise at 12:48 and a set at 3:05, along with a flat line at the lower end.

2. For my friend in Fairbanks, AK, there is no dawn or dusk. It should show a flat high line, but instead shows a flat low line.

I also noticed that the app uses dawn/dusk times instead of sunrise/sunset times. Not necessarily a bug, but it threw me off because Fairbanks does have sunrise/sunset.

![42963565-2166-4C62-AEC1-7053A29F4B9B](https://user-images.githubusercontent.com/6037480/83138783-2d184c00-a0a0-11ea-86df-8a16a08c0bda.jpeg)

---
Time Lines 1.0.3 (47) - me.dutour.mathieu.TimeLine
macOS 13.3.0
D22AP

**Comment by mathieudutour** [comment]
> The graphic does not handle the post-midnight dusk properly

Ouch, I'll see if I can spot the bug!

> I also noticed that the app uses dawn/dusk times instead of sunrise/sunset times.

I'm not sure what's the difference 😬 The app is using the Civil (6° below horizon) sunrise/sunset if that helps.

**Comment by strey1998** [comment]
> The app is using the Civil (6° below horizon) sunrise/sunset if that helps.

I see. In my experience that's usually referred to as civil twilight or civil dawn/dusk, while sunrise and sunset are reserved specifically for when the sun is at horizon. It makes sense to use that, I've just never seen it referred to as sunrise/sunset before.

**Comment by mathieudutour** [comment]
Should be fixed in 1.0.4 (currently being reviewed). Let me know if that's all good!

**Comment by strey1998** [comment]
Fairbanks works perfectly now. My only remaining quibble with Anchorage is that it appears to indicate that the sun rises slowly from dawn until midnight and then falls suddenly after midnight. However, I understand that your app is not intended as  a precise sun altitude calculator. With that in mind, I’ll agree the matter is resolved.
![81491FD7-621A-4939-8C39-3ADE4F579F25](https://user-images.githubusercontent.com/6037480/83695967-1bf3a180-a5b0-11ea-9237-ea97b4117405.jpeg)

**Comment by mathieudutour** [comment]
Yeah at the moment, if the dawn/twilight times aren't in the current day, I make the line end the top. I might be able to compute the sun position at midnight but it will take longer and I wanted to get a version that looks like something out of the door asap :)
