### ISSUE TITLE
Kuurne, Belgium issue

### ISSUE THREAD

**Issue by dnedrow** [mathieudutour/TimeLines#36]
I live in the US (Eastern Time Zone). I added a contact in Kuurne, Belgium, but the display for that contact was garbled. 

Here is a link to a screenshot (PDF) of the problem:

https://www.dropbox.com/s/8dqpfvgz6ltv8xs/IMG_2805.PNG?dl=0

**Comment by mathieudutour** [comment]
Funky! I made a new version that should fix that (in review currently). Let me know if it's all good after!
