### ISSUE TITLE
add contact from iOS contacts list

### ISSUE THREAD

**Issue by akac** [mathieudutour/TimeLines#37]
Some names are too difficult to type/spell. Also from their address you should be able to identify what time zone they are in. 

---
Time Lines 1.0.5 (51) - me.dutour.mathieu.TimeLine
macOS 13.5.1
D421AP

**Comment by mattballo** [comment]
Hi, @mathieudutour is this feature still available to implement?

**Comment by mathieudutour** [comment]
it hasn't been implemented yes

**Comment by mattballo** [comment]
Can you assign me to this issue, please?

**Comment by mattballo** [comment]
@mathieudutour can you please check my pull request?
