### ISSUE TITLE
[Feedback] Edit state can’t see names

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#4]
When editing, you can’t see names do it’s hard to know who you’re deleting. 

![D7BAA3A7-C64F-4BAE-90E5-A669F9933632](https://user-images.githubusercontent.com/371114/80084023-b500b880-852c-11ea-8d9d-503c76e3692c.png)

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
good point, it should probably be the other way around

**Comment by mathieudutour** [comment]
So I think it's actually a bug in SwiftUI:
- it is not supposed to show the line when in edit mode (https://github.com/mathieudutour/TimeLines/blob/master/TimeLineShared/TimeLineShareIOS/ContactRow.swift#L42)
- the editMode does change to `active` when clicking on the edit button
- it changes back directly to `inactive` (but shouldn't)

**Comment by mathieudutour** [comment]
managed to find a workaround
