### ISSUE TITLE
[Feedback] 

### ISSUE THREAD

**Issue by Tech-Aesthetic** [mathieudutour/TimeLines#42]
<img width="411" alt="Screen Shot 2020-06-14 at 5 21 38 PM" src="https://user-images.githubusercontent.com/32071811/84605517-8388d700-ae63-11ea-9549-9dd93b7ae2ea.png">

 this is certainly fun haha
---
Time Lines 1.0.7 (54) - me.dutour.mathieu.TimeLine
macOS 10.15.5
MacBookPro16,1
Timezone America/Chicago

**Comment by mathieudutour** [comment]
Thanks for the report! I think it's the same as #39 so I'm going to close this in favor of that one
