### ISSUE TITLE
[Feedback] 

### ISSUE THREAD

**Issue by zebdro** [mathieudutour/TimeLines#47]
The watch app does not sync for me. Uninstalling and reinstalling does not fix. It just shows the message to add contacts on my iPhone. 

---
Time Lines 1.0.8 (55) - me.dutour.mathieu.TimeLine
iOS 14.1.0
D22AP
Timezone America/Mexico_City

**Comment by mathieudutour** [comment]
duplicates of https://github.com/mathieudutour/TimeLines/issues/41
