### ISSUE TITLE
[Feedback] Me view

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#5]
Might be nice to see me in there 

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
As you noticed, I'm asking for as few permissions as possible, which means no location data.

I'm wondering whether the privacy concern outweighs the nice empty state that an automatic "Me" contact would be

**Comment by paintedbicycle** [comment]
Yeah totally fair. Might just be part of onboarding where you ask my time zone and nothing more

**Comment by paintedbicycle** [comment]
(Also as with all my other feedback, feel completely free to just close as `wontfix`)

**Comment by mathieudutour** [comment]
This "contact" could also be a bit special in the sense that you could scrub on the timeline to change the current time and see how the other contacts move on their respective timelines

https://twitter.com/nikolasklein/status/1253266785094303744?s=20

**Comment by paintedbicycle** [comment]
Yup, that could be cool too!

**Comment by mathieudutour** [comment]
fixed. I actually don't need to ask for the location, I can infer a pretty rough one from the current timezone. Not perfect but better than showing an alert.

Splitting the scrubbing to another issue
