### ISSUE TITLE
Crashing on M1 MacBook Air

### ISSUE THREAD

**Issue by OasisX** [mathieudutour/TimeLines#53]
Hi there

I think I messaged you about a year ago as on the M1 MacBooks your app keeps crashing (when selecting contact). I recall you saying you'd get an M1 so you can fix it... just wondering if you have an ETA as I would really love to use your app. I'm COO of our company and we have employees globally so using your app would be really useful! 

Thanks,
John

---
Time Lines 1.0.8 (55) - me.dutour.mathieu.TimeLine
macOS 10.16.0
MacBookAir10,1
Timezone Australia/Sydney

**Comment by mathieudutour** [comment]
should be fixed now
