### ISSUE TITLE
[Feedback] empty state

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#6]
First fun experience (empty state) was a little plain. Perhaps add the user as the first contact to show what it’ll look like? Or prod me on some other way to get started?

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
Good point, closing this in favor of #5 as it's related I think

**Comment by mathieudutour** [comment]
although an illustration could be the alternative

**Comment by paintedbicycle** [comment]
Oh yeah that could be nice

**Comment by mathieudutour** [comment]
I don't think an illustration makes too much sense now, the first screen is already quite full with the "Me" contact and the search bar
