### ISSUE TITLE
[Feedback] Reversed / grouped view

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#7]
Might be interesting with a lot of contacts in the same time zones to group them in some way. Like show Eastern time as the name and list all the people 

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
I'm going to close this one, the search/filter makes more sense to me I think
