### ISSUE TITLE
[Feedback] search and filter the contact list

### ISSUE THREAD

**Issue by paintedbicycle** [mathieudutour/TimeLines#8]
If I’m looking for one person in a long list, might be nice to search 

---
Time Lines 1.0.1 (27) - me.dutour.mathieu.TimeLine
macOS 13.4.1
D421AP

**Comment by mathieudutour** [comment]
Related: it could be nice to be able to add "tags" to a contact. So you can tag your team and when you search for "team", they all show up

**Comment by paintedbicycle** [comment]
Nice, yeah!

**Comment by mathieudutour** [comment]
fixed
